### ISSUE TITLE
spark 1.4

### ISSUE THREAD

**Issue by sarlam** [mliroz/hadoop_g5k#5]
Hello,
I'm trying to use spark_g5k with spark 1.4. I tried with both hadoop 2.4 and 2.6 but it have the same issue.
Here is what I got after deploying spark 1.4 with hadoop 2.6 

    (10:26 pjarleton@granduc-9 ~) > spark_g5k --shell scala
    15/07/10 08:26:39 INFO spark.SparkContext: Running Spark version 1.4.0
    15/07/10 08:26:39 INFO spark.SparkContext: Spark configuration:
    spark.app.name=Spark shell
    spark.driver.memory=1g
    spark.eventLog.dir=/tmp/spark/logs/events
    spark.eventLog.enabled=true
    spark.executor.memory=1507m
    spark.jars=
    spark.logConf=true
    spark.master=yarn-client
    spark.repl.class.uri=http://172.16.176.9:44723
    [...]
    15/07/10 08:26:53 INFO yarn.Client: Application report for application_1436516704093_0001 (state: RUNNING)
    15/07/10 08:26:53 INFO yarn.Client: 
         client token: N/A
         diagnostics: N/A
         ApplicationMaster host: 172.16.176.9
         ApplicationMaster RPC port: 0
         queue: default
         start time: 1436516803974
         final status: UNDEFINED
         tracking URL: http://granduc-9.luxembourg.grid5000.fr:8088/proxy/application_1436516704093_0001/
         user: pjarleton

    [...]
    15/07/10 08:26:53 ERROR spark.SparkContext: Error initializing SparkContext.
    java.io.FileNotFoundException: File file:/tmp/spark/logs/events does not exist

I read the script and try by my self to find out a solution but I couldn't and I try to read both spark 1.2 and 1.4 documentation to find a change but I didn't find anything.

Do you have ideas to make spark-g5k 1.4 ready, or ideas where I should look to improve the script ?

Have a nice day.

**Comment by nirvanesque** [comment]
Aha ! Finalement, quelqu'un qui a trouvé spark_g5k intéressant ! Excellent ! 
J'ai eu les mêmes problèmes avec hadoop_g5k et spark_g5k, à l'Exéco. 
Laurent et Miguel, la seule version stable de Hadoop qui marche bien avec vos scripts, est de 1.2.1 

Comme Workaround, j'ai donc rébuildé Spark avec Hadoop 1.2.1 et ai déployé avec hadoop_g5k 
Par ailleurs, il est alors nécessaire sbt (Scala Build Tool), soit localement soit sur G5K ( https://www.grid5000.fr/mediawiki/index.php/SBT_installation ). 

Surely, you have a better solution; please suggest. 
Je souhaiterai bien actualiser votre wiki à ce sens là. 

Merci par avance, 
Anirvan 

----- Original Message -----

**Comment by sarlam** [comment]
hadoop 1.2.1 ? 

J'ai fait tourner spark_g5k avec spark 1.2 et hadoop 2.4, c'est lorsque je passe spark à 1.4 que plus rien ne fonctionne. (seulement mon script necessite spark 1.4)

je vais essayer avec spark 1.4 + hadoop 1.2.1.

**Comment by mliroz** [comment]
The problem is that the directory corresponding to spark argument ```spark.eventLog.dir``` is not created. It seems to me that in previous versions of Spark it was created automatically, and from version 1.4 it is not. In fact, I have tried previous versions of Spark with Hadoop 2.x and worked in both STANDALONE and YARN modes.

I will correct that taking into account that this directory may be a local directory but also be a HDFS directory. I will also turn back to Spark's defaults (no event logging). As a workaround you may create the directory by yourselves.

**Comment by sarlam** [comment]
I tried to create the directory and even the file, in both case it doesn't work.

I did it before,

     spark_g5k --initialize --start

**Comment by mliroz** [comment]
I think that somehow ```--initialize``` or ```--start``` voids the logs dir. Since the default events directory in the current version of ```spark_g5k``` is inside, it is removed. It should work if you do it after ```--start```.
